### ISSUE TITLE
files can be written outside of the settings store

### ISSUE THREAD

**Issue by individual-it** [owncloud/ocis-settings#15]
when creating a settings bundle the Extension and the BundleKey are used to create the folder and the file-name to store the settings. It looks like those values are not checked, any files/folders can be created outside of the settings store. e.g by passing in `../` as BundleKey

So far only tested using the GRPC service, but I guess that would also work using the HTTP service

**Comment by kulmann** [comment]
We should at least forbid `.` and `/` as BundleKey. Maybe even restrict the allowed characters to alphanumerical, `-` and `_` only.

**Comment by individual-it** [comment]
same applies to `GetSettingsBundle()` potentially any (json) file on the system can be read

**Comment by individual-it** [comment]
same applies to `SaveSettingsValue()`
