### ISSUE TITLE
random CI failures

### ISSUE THREAD

**Issue by kulmann** [owncloud/ocis-settings#30]
CI randomly fails in different pipelines with the following error message:

```
protoc \
		-I=third_party/ \
		-I=pkg/proto/v0/ \
		--go_out=pkg/proto/v0 settings.proto
	protoc-gen-go: program not found or is not executable
	Please specify a program using absolute path or make sure the program is available in your PATH system variable
	--go_out: protoc-gen-go: Plugin failed with status code 1.
	make: *** [Makefile:173: pkg/proto/v0/settings.pb.go] Error 1
```

The `program not found or is not executable` error appears randomly for:
- protoc-gen-go
- protoc-gen-micro
- protoc-gen-microweb

Example CI run: https://cloud.drone.io/owncloud/ocis-settings/106/3/4 

Needs investigation.

**Comment by kulmann** [comment]
Same happens in ocis-accounts (e.g. https://cloud.drone.io/owncloud/ocis-accounts/387/2/5) and ocis-hello

**Comment by kulmann** [comment]
According to e.g. https://cloud.drone.io/owncloud/ocis-settings/277/1/7 protoc can't find `protoc-gen-micro`, `protoc-gen-microweb` etc.

Looking into our Makefile, those are installed into the `$GOPATH`:
https://github.com/owncloud/ocis-settings/blob/5249eeca3ff5ff50eb6fa7a8ef3061f1958a8c27/Makefile#L160

Now looking at the docker image we're using:
- sets the `$GOPATH` as `/srv/app`, see https://github.com/dockhippie/golang/blob/b81c833b9a1eb5244e4c381368a40a9fd811a8ba/v1.13/Dockerfile.amd64#L18
- doesn't include `$GOPATH/bin` in `$PATH`, see https://github.com/dockhippie/golang/blob/b81c833b9a1eb5244e4c381368a40a9fd811a8ba/v1.13/Dockerfile.amd64#L19 
I'm wondering how this ever worked. Looking at the env vars, protoc is not able to find `protoc-gen-micro` by design.

Does anyone know why the `$GOPATH` is set to a directory that looks like it's supposed to serve a compiled binary and not have any other go binaries in it?

**Comment by kulmann** [comment]
On second thought, we check the generated proto code into our codebase anyway. Why do we need to run protoc at all? 🤔

**Comment by kulmann** [comment]
@C0rby see the comments here and this PR https://github.com/owncloud/ocis-settings/pull/54
Drone is still failing though, so changing from `go get` to `go install` didn't help.

**Comment by kulmann** [comment]
You can find the Dockerfile we're using here:  https://github.com/dockhippie/golang/blob/master/v1.13/Dockerfile.amd64

**Comment by C0rby** [comment]
GOBIN is included to the PATH by `/srv/app/bin` https://github.com/dockhippie/golang/blob/master/v1.13/Dockerfile.amd64#L19. So that should not be the problem

**Comment by kulmann** [comment]
This issue has been resolved by explicitly including the `protobuf` step before `build` steps in .drone.star.
It still is odd and counts as a workaround, because we didn't find out why `protoc` is called in the build step in the first place. Forcing the `protobuf` step before `build` just makes sure that the required `protoc` plugins are installed properly. But it's not an explanation, why protoc runs during build...
